---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media
  nfs:
    server: 172.16.50.4
    path: "/volume1/data/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 100Gi
