# k3s-nfs-bind-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mediacenter
  namespace: mediacenter
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-mediacenter
  resources:
    requests:
      storage: 100Gi
