---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mediacenter
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediacenter
  nfs:
    server: 172.16.50.4
    path: "/volume1/mediacenter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mediacenter
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediacenter
  resources:
    requests:
      storage: 100Gi
