apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-uhd
  namespace: mediacenter
  labels:
    app: sonarr-uhd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr-uhd
  template:
    metadata:
      labels:
        app: sonarr-uhd
    spec:
      securityContext:
        fsGroup: 1000 
      nodeSelector:
        worker: "true"
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - mountPath: /config 
          name: config  
      - name: config
        image: busybox
        command: ["sh", "-c"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        args:
          - "echo start;[[ ! -f /config/config.xml ]] && echo '<Config><UrlBase>/sonarr-uhd</UrlBase></Config>'> /config/config.xml;echo end;"
        volumeMounts: 
        - mountPath: /config 
          name: config 
      containers:
        - name: sonarr
          image: linuxserver/sonarr
          ports:
            - containerPort: 8989
              name: webui
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:8989/sonarr-uhd/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:8989/sonarr-uhd/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: /data
              name: mediacenter
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-uhd-pvc
        - name: mediacenter
          persistentVolumeClaim:
            claimName: nfs-mediacenter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-uhd-pvc
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr-uhd
  name: sonarr-uhd
  namespace: mediacenter
spec:
  selector:
    app: sonarr-uhd
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989