---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: media
  labels:
    app: nginx
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: media
spec:
  selector:
    app: nginx
  ports:
  - name: http
    targetPort: 80
    port: 80
