---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-local-krlab-tech
  namespace: cattle-system
spec:
  commonName: rancher.local.krlab.tech
  dnsNames:
    - rancher.local.krlab.tech
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-rancher-ingress
