apiVersion: builtin
kind: LabelTransformer
metadata:
  name: radarr
labels:
  app: radarr-4k
fieldSpecs:
- kind: Deployment
  path: metadata/labels
  create: true
- kind: Deployment
  path: spec/template/metadata/labels
  create: true
- kind: Deployment
  path: spec/selector/matchLabels
  create: true
- kind: Service
  path: metadata/labels
  create: true
- kind: Service
  path: spec/template/metadata/labels
  create: true
- kind: PersistentVolumeClaim
  path: metadata/labels
  create: true
