---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-krlab-tech
  namespace: default
spec:
  secretName: local-krlab-tech-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.krlab.tech"
  dnsNames:
    - "local.krlab.tech"
    - "*.local.krlab.tech"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,longhorn-system,pihole" # Control auto-reflection namespaces

