---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dddd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-amk
  namespace: default
spec:
  containers:
  - name: volume-amk
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: dddd