---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd
  namespace: mediacenter
spec:
  type:  ClusterIP
  selector:
    app: sabnzbd
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
