apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-amk
spec:
  storageClassName: nfs-client
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-amk
spec:
  nodeSelector:
    worker: "true"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: nginx-amk
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html