---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: mediacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      nodeSelector:
        worker: "true"
      runtimeClassName: nvidia
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: "1" # requesting 1 GPU
        ports:
        - containerPort: 8096
          name: web
          protocol: TCP
        env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: "Europe/Berlin"
          - name: NVIDIA_VISIBLE_DEVICES
            value: "all"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "all"
          - name: CUDA_DRIVER_CAPABILITIES
            value: "all"
        volumeMounts:
        - mountPath: /config
          name: jellyfin-config
        - mountPath: /data
          name: mediacenter
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: mediacenter
          persistentVolumeClaim:
            claimName: nfs-mediacenter-xxx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: mediacenter 
spec:
  type: LoadBalancer
  ports:
  - name: web-tcp
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: web-udp
    port: 8096
    protocol: UDP
    targetPort: 8096
  selector:
    app: jellyfin
