---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mediacenter-xxx
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-mediacenter-xxx
  nfs:
    server: 172.16.50.4
    path: "/volume1/PT"
