---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisparr-config-pvc
  namespace: whisparr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi