apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: mediacenter
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      securityContext:
        fsGroup: 1000 
      nodeSelector:
        worker: "true"
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        volumeMounts:
        - mountPath: /config 
          name: config
      - name: config
        image: busybox
        command: ["sh", "-c"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        args:
          - "echo start;[[ ! -f /config/config.xml ]] && echo '<Config><UrlBase>/$(RADARR)</UrlBase></Config>'> /config/config.xml;echo end;"
        volumeMounts: 
        - mountPath: /config 
          name: config
      containers:
        - name: radarr
          image: linuxserver/radarr
          ports:
            - containerPort: 7878
              name: webui
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:7878/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl "http://localhost:7878/radarr/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: /data
              name: mediacenter
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-radarr
        - name: mediacenter
          persistentVolumeClaim:
            claimName: nfs-mediacenter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr
  namespace: mediacenter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  ports:
    - port: 7878
      protocol: TCP
      targetPort: 7878
      name: webui
  selector:
    app: radarr
