---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media-smb
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-media-smb
  storageClassName: smb