kind: Service
apiVersion: v1
metadata:
  name: proxmox
  namespace: external-websites
spec:
  type: ExternalName
  externalName: 172.16.50.3
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: external-websites
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.proxmox.local.krlab.tech`)
      kind: Rule
      services:
        - name: rackstation
          port: 8006
          scheme: https
          passHostHeader: true
    - match: Host(`proxmox.local.krlab.tech`)
      kind: Rule
      priority: 1
      services:
        - name: proxmox
          port: 8006
      middlewares:
        - name: default-headers
  tls:
    secretName: local-krlab-tech-tls
