kind: Service
apiVersion: v1
metadata:
  name: rackstation
  namespace: external-websites
spec:
  type: ExternalName
  externalName: 172.16.50.4
  ports:
    - name: https
      port: 5001
      targetPort: 5001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rackstation
  namespace: external-websites
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rackstation.local.krlab.tech`)
      kind: Rule
      priority: 1
      services:
        - name: rackstation
          port: 5001
          passHostHeader: true
      middlewares:
        - name: default-headers
  tls:
    secretName: local-krlab-tech-tls
