---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: krlab # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: krlab-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.krlab.tech" # change to your domain
  dnsNames:
  - "*.krlab.tech" # change to your domain
  - krlab.tech # change to your domain