---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-bind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---