apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../../base

commonLabels:
  app: radarr-4k

nameSuffix: "-4k"


patches:
  - path: deployment.yaml
  - path: service.yaml
  - target:
      kind: IngressRoute
      name: mediacenter
    path: ingress-patch.yaml

configurations:
- skip-suffix.yaml