---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: mediacenter
spec:
  selector:
    app: sonarr
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989