---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-data
  nfs:
    server: 172.16.50.4
    path: "/volume1/htcp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 100Gi