# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: notifiarr-config-pvc
#   namespace: mediacenter
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 10Gi